apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: "3.9.x"
      sourceRef:
        kind: HelmRepository
        name: openebs-repo
        namespace: kube-system
      interval: 12h
  # https://github.com/openebs/charts/blob/chart-3.9.0/charts/openebs/values.yaml
  values:
    # Directory used by the OpenEBS to store debug information and so forth
    # that are generated in the course of running OpenEBS containers.
    varDirectoryPath:
      baseDir: "/var/openebs"

    crd:
      enableInstall: true

    policies:
      monitoring:
        enabled: true

    analytics:
      enabled: true
      # Specify in hours the duration after which a ping event needs to be sent.
      pingInterval: "24h"

    provisioner:
      enabled: true
      replicas: 1

    localprovisioner:
      enabled: true
      replicas: 1
      enableDeviceClass: true
      enableHostpathClass: true
      # This sets default directory used by the provisioner to provision
      # hostpath volumes.
      basePath: "/var/openebs/local"

      deviceClass:
        name: openebs-device
        enabled: true
        # Sets the filesystem to be written to the blockdevice before
        # mounting (filesystem volumes)
        # This is only usable if the selected BlockDevice does not already
        # have a filesystem
        # Valid values: "ext4", "xfs"
        fsType: "ext4"

      hostpathClass:
        name: openebs-hostpath
        enabled: true
        isDefaultClass: false
        # Path on the host where local volumes of this storage class are mounted under.
        # NOTE: If not specified, this defaults to the value of localprovisioner.basePath.
        basePath: ""

    snapshotOperator:
      enabled: true
      replicas: 1

    ndm:
      enabled: false

    mayastor:
      enabled: false

    jiva:
      enabled: false

    openebs-ndm:
      enabled: false

    localpv-provisioner:
      enabled: false
      openebsNDM:
        enabled: false

    zfs-localpv:
      enabled: false

    lvm-localpv:
      enabled: false

    nfs-provisioner:
      enabled: false
