kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-redis
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs: '[ { "name":"miha-redis-snap", "task":"snapshot", "cron":"*/30 * * * *", "retain":6 }, { "name":"miha-redis-backup", "task":"backup", "cron":"0 */6 * * *", "retain":12 } ]'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: miha-longhorn-redis
  resources:
    requests:
      storage: 5Gi
