apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    detail: redis
    app: miha
spec:
  replicas: 1
  selector:
    matchLabels:
      detail: redis
      app: miha
  template:
    metadata:
      labels:
        detail: redis
        app: miha
    spec:
      containers:
      - name: redis
        image: redislabs/redismod
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    detail: redis
    app: miha
spec:
  selector:
    detail: redis
    app: miha
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
