apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-monitor
spec:
  selector:
    matchLabels:
      detail: redis
      app: miha
  namespaceSelector:
    matchNames:
    - miha
  endpoints:
  - targetPort: 9121
    path: /metrics
    interval: 30s
