apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    detail: redis
    app: miha
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
kind: Service
metadata:
  name: redis-exporter-service
spec:
  selector:
    detail: redis
    app: miha
  ports:
  - protocol: TCP
    port: 9122
    targetPort: 9121
