apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |-
    maxmemory 256
    maxmemory-policy allkeys-lru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    detail: redis
    app: miha
spec:
  replicas: 1
  selector:
    matchLabels:
      detail: redis
      app: miha
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        detail: redis
        app: miha
    spec:
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      containers:
      - name: redis
        image: redislabs/redismod
        volumeMounts:
        - name: redis-config
          mountPath: /redis/etc
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        env:
        - name: REDIS_EXPORTER_PING_ON_CONNECT
          value: "true"
        - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
          value: "true"
        securityContext:
          runAsUser: 59000
          runAsGroup: 59000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 9121
