apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-seal-repo
  namespace: kube-system
spec:
  interval: 24h
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-seal-release
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-seal
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: kube-seal-repo
        namespace: kube-system
      interval: 12h
  values:
# metrics.serviceMonitor.enabled: true TODO
# metrics.serviceMonitor.namespace: "" # TODO
