apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-secrets-webhook
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: bank-vaults-vault-secrets-webhook-repo
      interval: 12h
  # https://github.com/bank-vaults/vault-secrets-webhook/blob/main/deploy/charts/vault-secrets-webhook/values.yaml
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
