apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-operator
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: bank-vaults-repo
        namespace: vault
      interval: 12h
  values:
