apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-secrets
  namespace: vault
spec:
  interval: 1m
  approvePlan: "auto"
  path: ./cluster/secrets/vault-secrets
  writeOutputsToSecret:
  name: vault-secrets-output
  outputs:
  - vault_namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
  - name: vault_namespace
    value: vault
