apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bank-vaults-repo
  namespace: vault
spec:
  interval: 24h
  url: https://kubernetes-charts.banzaicloud.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: bank-vaults-repo
        namespace: vault
      interval: 12h
  values:
    unsealer:
      args: ["--mode", "k8s", "--k8s-secret-namespace", "vault", "--k8s-secret-name", "bank-vaults"]
    vault:
      externalConfig:
        auth:
        - type: kubernetes
          roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook"]
            bound_service_account_namespaces: ["default", "vault"]
            policies: allow_secrets
            ttl: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-operator
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: bank-vaults-repo
        namespace: vault
      interval: 12h
  values:
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-secrets-webhook
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: bank-vaults-repo
        namespace: vault
      interval: 12h
  values:
---
