apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-secrets
  namespace: vault
spec:
  interval: 1m
  approvePlan: "auto"
  path: ./cluster/secrets/vault-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  writeOutputsToSecret:
    name: vault-secrets-output
  vars:
  - name: vault_namespace
    value: vault
