apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-secrets
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: "auto"
  path: ./cluster/secrets/vault-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  writeOutputsToSecret:
    name: vault-secrets-output
  runnerPodTemplate:
    spec:
      env:
      - name: VAULT_TOKEN
        value: vault:login
  vars:
  - name: vault_namespace
    value: vault:login
