apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-env
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-secrets
  namespace: vault
spec:
  interval: 1m
  approvePlan: "auto"
  path: ./cluster/secrets/vault-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  writeOutputsToSecret:
    name: vault-secrets-output
  runnerPodTemplate:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/mutate-configmap: "vault-env"
    spec:
      env:
      - name: VAULT_TOKEN
        value: vault:login
  varsFrom:
  - kind: Secret
    name: bank-vaults
    varsKeys:
    - vault-root
  - kind: Secret
    name: vault-tls
    varsKeys:
    - ca.cert
    - ca.key
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tf-runner-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-runner-role
subjects:
- kind: ServiceAccount
  name: tf-runner
  namespace: vault
