apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: miha

namespace: miha
namePrefix: miha-prod-

commonLabels:
  app: miha
  stack: prod

resources:
- ../base
- secret-discord.yaml

patchesStrategicMerge:
- deplyoment.yaml
- redis.yaml
