apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: miha

resources:
- ../base
- secret-discord.yaml

labels:
- includeSelectors: true
  pairs:
    app: miha
    detail: bot
    stack: prod

patches:
- path: stateful.yaml
- path: metrics.yaml
