apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-metrics
spec:
  selector:
    matchLabels:
      stack: prod
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-redis
provisioner: driver.longhorn.io
parameters:
  recurringJobs: ''
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: miha-prod-longhorn-redis
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      volumes:
      - name: miha-redis-data
        persistentVolumeClaim:
          claimName: miha-prod-redis-pvc
