apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: miha
spec:
  template:
    spec:
      containers:
      - name: miha
        image: ghcr.io/catboy-den/miha:0.2.3 # {"$imagepolicy": "flux-system:miha-latest"}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: DOTNET_DISCORD__TOKEN
          valueFrom:
            secretKeyRef:
              name: miha-discord
              key: token
        - name: DOTNET_DISCORD__GUILD
          valueFrom:
            secretKeyRef:
              name: miha-discord
              key: guild-id
