apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: miha
spec:
  template:
    spec:
      containers:
      - name: miha
        image: ghcr.io/twinki14/miha:latest # {"$imagepolicy": "flux-system:miha-latest"}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: DOTNET_REDIS__SEEDING__GUILD__AnnouncementChannel
          value: '397604957962108931'
        - name: DOTNET_REDIS__SEEDING__GUILD__AnnouncementRoleId
          value: '517819199863914516'
        - name: DOTNET_REDIS__SEEDING__GUILD__WeeklyScheduleChannel
          value: '480114580664877060'
        - name: DOTNET_DISCORD__TOKEN
          valueFrom:
            secretKeyRef:
              name: miha-discord
              key: token
        - name: DOTNET_DISCORD__GUILD
          valueFrom:
            secretKeyRef:
              name: miha-discord
              key: guild-id
