apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repo
        namespace: kube-system
      interval: 12h
  values:
# metrics.serviceMonitor.enabled: true TODO
# metrics.serviceMonitor.namespace: "" # TODO
