apiVersion: v1
kind: Service
metadata:
  name: redis-metrics-service
spec:
  selector:
    component: redis-prod-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-metrics
spec:
  selector:
    matchLabels:
      component: redis-prod-metrics
      stack: prod
