apiVersion: v1
kind: Secret
metadata:
  name: dex-flux-values
  namespace: dex
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
stringData:
  values: |-
    serviceMonitor:
      enabled: true
    config:
      issuer: https://dex.catboy.rest
      storage:
        type: kubernetes
        config:
          inCluster: true
      oauth2:
        skipApprovalScreen: true
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          redirectURI: https://dex.catboy.rest/callback
          loadAllGroups: false
          teamNameField: slug
          useLoginAsID: false
          orgs:
            - name: catboy-den
              teams:
              - cluster-admin
              - cluster-user
      staticClients:
        - id: weave-gitops
          redirectURIs:
          - 'https://weave.catboy.rest/oauth2/callback'
          name: 'Weave Gitops'
          secret: ${vault:secret/data/dex-staticClient-secret#secret}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: dex.catboy.rest
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dex.catboy.rest
          secretName: dex-cert
