apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-static-clients
  namespace: dex
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
type: Opaque
data:
  staticClients: fuck
