apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-flux-values
  namespace: dex
data:
  values: |-
    serviceMonitor:
      enabled: true
    config:
      issuer: https://dex.catboy.rest
      storage:
        type: kubernetes
        config:
          inCluster: true
      oauth2:
        skipApprovalScreen: true
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          redirectURI: https://dex.catboy.rest/callback
          loadAllGroups: false
          teamNameField: slug
          useLoginAsID: false
          orgs:
            - name: catboy-den
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: dex.catboy.rest
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dex.catboy.rest
          secretName: dex-cert
