apiVersion: v1
kind: Namespace
metadata:
  name: dex
  labels:
    sealedSecret: github-oauth
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
spec:
  interval: 24h
  url: https://charts.dexidp.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-flux-values
  namespace: dex
data:
  values.yaml: |
    serviceMonitor:
      enabled: true
    config:
      issuer: https://dex.catboy.rest
      storage:
        type: kubernetes
        config:
          inCluster: true
      oauth2:
        skipApprovalScreen: true
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          redirectURI: https://dex.catboy.rest/callback
          loadAllGroups: false
          teamNameField: slug
          useLoginAsID: false
          orgs:
            - name: catboy-den
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: dex.catboy.rest
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dex.catboy.rest
          secretName: dex-cert
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 30m
  chart:
    spec:
      chart: dex
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: dex
      interval: 12h
  valuesFrom:
  - kind: ConfigMap
    name: dex-flux-values
    valuesKey: values.yaml
    optional: false
  - kind: Secret
    name: dex-static-clients
    valuesKey: staticClients.yaml
    targetPath: config
    optional: false
