apiVersion: v1
kind: Namespace
metadata:
  name: dex
  labels:
    sealedSecret: github-oauth
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
spec:
  interval: 24h
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 30m
  chart:
    spec:
      chart: dex
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: dex
      interval: 12h
  valuesFrom:
  - kind: Secret
    name: dex-flux-values
    valuesKey: values
    optional: false
  - kind: Secret
    name: github-oauth
    valuesKey: client-id
    targetPath: config.connectors[0].config.clientID
    optional: false
  - kind: Secret
    name: github-oauth
    valuesKey: client-secret
    targetPath: config.connectors[0].config.clientSecret
    optional: false
