apiVersion: v1
kind: Namespace
metadata:
  name: dex
  labels:
    sealedSecret: github-oauth
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
spec:
  interval: 24h
  url: https://charts.dexidp.io
---
