apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
spec:
  interval: 30m
  suspend: false
  chart:
    spec:
      chart: vault-operator
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: bank-vaults-repo
      interval: 12h
  # https://github.com/bank-vaults/vault-operator/tree/main/deploy/charts/vault-operator
  values:
    monitoring:
      serviceMonitor:
        enabled: true
