apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: appscode-repo
  namespace: kube-system
spec:
  interval: 24h
  url: https://charts.appscode.com/stable/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kubed
      version: "0.12.x"
      sourceRef:
        kind: HelmRepository
        name: appscode-repo
        namespace: kube-system
      interval: 12h
