apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emberstack-repo
  namespace: kube-system
spec:
  interval: 24h
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: "v7.x"
      sourceRef:
        kind: HelmRepository
        name: emberstack-repo
        namespace: kube-system
      interval: 12h
