kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-redis
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs: '[ ]'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: miha-longhorn-redis
  resources:
    requests:
      storage: 5Gi
