apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubernetes-secret-generator
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.mittwald.de
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-secret-generator
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kubernetes-secret-generator
      version: "x"
      sourceRef:
        kind: HelmRepository
        name: kubernetes-secret-generator
        namespace: kube-system
      interval: 12h
