kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-valheim
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs: '[ ]'
