apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
spec:
  selector:
    matchLabels:
      app: nginx-rtmp
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: alqutami/rtmp-hls:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: rtmp-port
          containerPort: 1935
        - name: http-port
          containerPort: 80
      restartPolicy: Always
