apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: IngressName
  namespace: default
spec:
  rules:
  - host: stream.catboy.rest
    http:
      paths:
      - path: /live
        pathType: Prefix
        backend:
          service:
            name: nginx-rtmp
            port:
              number: 1935
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-rtmp
            port:
              number: 80
