apiVersion: v1
kind: namespace
metadata:
  name: vault
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vault-repo
  namespace: vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-release
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: vault-repo
        namespace: vault
      interval: 12h
  values:
# metrics.serviceMonitor.enabled: true TODO, look into this
