apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      version: ">=0.15.0"
  interval: 1h0s
  releaseName: tf-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/values.yaml
  values:
    installCRDs: true
    metrics:
      # -- Enable Metrics Service
      enabled: true
      # ServiceMonitor
      serviceMonitor:
        # -- Enable ServiceMonitor
        enabled: true
    replicaCount: 1
    concurrency: 24
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 64Mi
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    awsPackage:
      install: false
