apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.4.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn-system
      interval: 12h
  # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
  values:
    longhornManager:
      log:
        ## Allowed values are `plain` or `json`.
        format: json
