apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-flux-secrets
  namespace: authentik
  annotations:
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/autogenerate: secret-key, postgres-pw
data:
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 24h
  url: https://charts.goauthentik.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-flux-values
  namespace: authentik
data:
  values: |
    authentik:
        error_reporting:
            enabled: true

    ingress:
        enabled: true
        hosts:
            - host: authentik.catboy.rest
              paths:
                  - path: "/"
                    pathType: Prefix

    postgresql:
        enabled: true
    redis:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2023.x"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 12h

  valuesFrom:
  - kind: ConfigMap
    name: authentik-flux-values
    valuesKey: values
  - kind: Secret
    name: authentik-flux-secrets
    valuesKey: secret-key
    targetPath: authentik.secret_key
  - kind: Secret
    name: authentik-flux-secrets
    valuesKey: postgres-pw
    targetPath: authentik.postgresql.password
  - kind: Secret
    name: authentik-flux-secrets
    valuesKey: postgres-pw
    targetPath: postgresql.postgresqlPassword
