apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides a simple way to get insights into your GitOps workloads.
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  values:
    additionalArgs:
      - --auth-methods=oidc
    envVars:
      - name: WEAVE_GITOPS_FEATURE_OIDC_BUTTON_LABEL
        value: "Login with GitHub"
      - name: WEAVE_GITOPS_FEATURE_CLUSTER_USER_AUTH
        value: "false"
      - name: CLUSTER_USER_AUTH
        value: "false"
    metrics:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: weave.catboy.rest
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - weave.catboy.rest
          secretName: weave-gitops-cert
    rbac:
      create: true
  interval: 1h
