apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repo
      interval: 12h
  # https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
  values:
    metrics:
      serviceMonitor:
        enabled: true
