apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: miha-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: miha-bot
  policy:
    semver:
      range: x.x.x
