apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: miha-edge
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: miha-bot
  filterTags:
    pattern: '^(cutting-edge-|edge-).*?-(?P<timestamp>\d+)$'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc
