apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
type: Opaque
stringData:
  api-key: 26J6wLM-NYQaH6Glp1CWvrseZwEqeeTY65BJMogA
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: thetwinkehh@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        cloudflare:
          email: thetwinkehh@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key
