apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-secrets
  namespace: vault
spec:
  interval: 1h
  approvePlan: "auto"
  path: ./cluster/auth/secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  writeOutputsToSecret:
    name: vault-secrets-output
  runnerPodTemplate:
    spec:
      env:
      - name: VAULT_ADDR
        value: https://vault.vault:8200
      - name: VAULT_CACERT
        value: /vault/tls/ca.crt
      volumeMounts:
      - mountPath: "/vault/tls"
        name: vault-tls
        readOnly: true
      volumes:
      - name: vault-tls
        secret:
          secretName: vault-tls
  varsFrom:
  - kind: Secret
    name: bank-vaults
    varsKeys:
    - vault-root
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tf-runner-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-runner-role
subjects:
- kind: ServiceAccount
  name: tf-runner
  namespace: vault
