apiVersion: v1
kind: Namespace
metadata:
  name: dex
  labels:
    sealedSecret: github-oauth
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
spec:
  interval: 24h
  url: https://charts.dexidp.io
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-flux-values
  namespace: dex
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
stringData:
  values: |-
    serviceMonitor:
      enabled: true
    config:
      issuer: https://dex.catboy.rest
      storage:
        type: kubernetes
        config:
          inCluster: true
      oauth2:
        skipApprovalScreen: true
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          redirectURI: https://dex.catboy.rest/callback
          loadAllGroups: false
          teamNameField: slug
          useLoginAsID: false
          orgs:
            - name: catboy-den
              teams:
              - cluster-admin
              - cluster-user
      staticClients:
        - id: weave-gitops
          redirectURIs:
          - 'https://weave.catboy.rest/oauth2/callback'
          name: 'Weave Gitops'
          secret: ${vault:secret/data/dex-staticClient-secret#secret}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: dex.catboy.rest
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dex.catboy.rest
          secretName: dex-cert
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 30m
  chart:
    spec:
      chart: dex
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: dex
      interval: 12h
  valuesFrom:
  - kind: Secret
    name: dex-flux-values
    valuesKey: values
    optional: false
  - kind: Secret
    name: github-oauth
    valuesKey: client-id
    targetPath: config.connectors[0].config.clientID
    optional: false
  - kind: Secret
    name: github-oauth
    valuesKey: client-secret
    targetPath: config.connectors[0].config.clientSecret
    optional: false
