apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: github-oauth
  namespace: kube-system
spec:
  encryptedData:
    client-id: AgAGyGrvMmh1YtcQ6bWm5XfCZ/UWP3sJo0jX0hLSX0eAAwXKVWmQm1e8foFVzPLS2qyQJJw0KWQUsv47ttHr2qET5ji4EMwkIYN8rKP5kTW7yvYx2yZ65qoh9zg6UhsE1Mg5/SUL3Gaf5F2w+SaRv65tzw4vFzPpP5fKRSQbtwcmPYFGt7A32t0KCTGc7hv68M/A0FIJ1S86QFjrqdTNOOssuHSyBhgyI8aEpQYXCEwAXSelqtrl+dJKrS5rSJwVq4fyv66A/srLKX/hb0FYBrf3mxNimj7YE3NxJVm2NbAtP7QXjXwps8c2IAMDBT/00/Ox9bLwJg3AD/5zJZJdgJBRCshSfhDUsi7jDfgn4MbbmL23RgFMvL3vieg7DsRVzavMlWygwvm395oB8hKDKRJZXJVR/knjGwAnI6FnnL54mnsElMaXIEvpIt9PZpYfcHTkb1vE3KxYfGemOTZlPUvJt9F3f9uiPylBHM9YsPnVFQDjB/XdlB9A7OSy3COeLAhagqYncipy3ihVrNpUL6IG0SRP//q5PjcJ+xqmOEsWXegNCFUwSG2U0logPQZYCtCwyqA+i9UiVs2Yn6Tz+lHwLuJLunN++VnDqHkRYyQ//cYRd+lFfzmx3dPJj4Tp3ZAf8S/tu+POmztD2W08W7j5juQLfjSKZax3e9NhnC1e6Qw2Gmnj7TTYmfCtwO0pNqyTG43clqN5Xz3YbA0qJsU=
    client-secret: AgCNkciTKRWnJutOeS4dgF+FFgErQMat2GjTkBMy/5nktfV7/bdhFoYKaO4WU8E8xu3oq/7xSOvVSqzemuHKagNYvmkquaslQrV6fR7Xl2PnZdLZTZM5Rem5jlIlnO6UkeaPIIadMhPzD46yQCmb+ri50OE0rwIlYfBTpykNqx2C+rjO9UP3D0RFtt8lI49iXtsfDoLJqisa2Imt6c96Z5gWZX1IX1x8W8HLYOkyznLuEh5tej87rgxOluKX8ajTDS8Msv6hcF5hUy+ublsxdXVFdD93IelIrMCdoUwjvZ0rxyt9zaXBKs0I81vck/HAY5YUds2A/aC9M+ddK9kjCp3sf0Ae2TeMtkYmpFuuLYRXAd/ZOlK5R0c+6Dx+kGMVG48uv4tINYRo+1+3W397jS3p6uOOcTzSSiUrk71m6HNvPX89RotyXG1hHktMWJ8Bn0Nyl5UHBuc0lbw3fW0MnM8EI2Gi8O0MwECfMPtNgnZemH8avbEVfJyXRWgeBKnPAF8AvpqzJxgSF9ikRrCtjhGZCotjSg1Rm0Z9IKud4NGm6Kw8PlQqfNqPbTmusjp4qekAGxYNzV0Q30b8psabuOe9MBxQjtMG4j6t8VpZex4eYz1Yhb/65/U1hMmW/kszjoldIPmRUagExH2nCnCcv9BEAtxhjoDX4OPWW9pZ6MCOhFija158D90zb5q6D932MVhBFDxHFNhd3Of85ZRXMDhM5ZZ33gaZd+3pOLwHh8E=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        kubed.appscode.com/sync: "sealedSecret=github-oauth"
      creationTimestamp: null
      name: github-oauth
      namespace: kube-system
