apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: github-oauth
spec:
  encryptedData:
    client-id: AgB5RNIkIhGHGX71oPqYUfuHUrmNQPCC29XtIhOt+riJ0E/+xfJEmLw5nEXv3zRiVvKsi3pccJO1f6RsKy+f6dxJG7Yb1VhVwibgilD5aZjjyvUfz3SNMRgKIKnr0YBBeAzu60N4cnNKnwPLCVFbK8IPt/jzKR/Z2zbxfd4hCwvZ12z+kso5narm9gvoBHBexmX9xl4OABrhnKuk3WNXi7tXJdxYoofRWzs2W15GU7x5d+V/s/VXXdaPoOU0AIvWezWUNoB59iOP+WhALA94WwdWS5v4MtFAECUniLWLPE3JnnUl2PtR7lRRdSj4F8X9PlNbOBTH8PZ2vJ8eHk7SQ0SGSifurrbWB74Ezut7eRMxfK7riV21Pl6acFWOkpQ1kmg3RnV3wyQANPmyxBgp2/jvFotGQ6wKdzykVTNpYGqRJronz4ejn+kzsxW9UY2CBdii5kWcpAkGRXbr8EL3Qjg/Ir0ahcAM0ueWAtWQ6QKk8/CiW1ctZErttTY+tZ3q9EzwsqNB4WHkfFF9kiLlEzBpQQmsTxuBsRytHqp68Zqb8NXTq7biu145NFWGT1PYk7n1DA/RycpCgyUDAEQM8WjVMnKM1la8RaA+d8MfyS4JW1JLRSDvm17rZJ35KTB1iWPm+ylF7x8+LUiIKOvePvmy4yaM52VPyVdTBtNmLSzOsJBMSUq+z2ai73YCqEux8L7f1w5iLAcKKz5wBgRknKkWIXXM0g==
    client-secret: AgA5Fik4YSh7FhQPBiJ2NRLFeETlMqY8MfIlcCDff+0wNjTePiae/odCqymK9jmvI/PEeel1N1i3gE+bQwGC52LawoALOZRt8Ps7Uq5VQOKvXeaaKZjbGd07pubT084QiWQzm6tcEc6Y7FcPWaU/E1L5BEyxVrvM7nfyc+vbqr3ihvyso0MRL4pQyau3tZyYEVDxP7BIf2F7H+fDAzV6krIMBiXQ5B6XpURrBFxlVBAleb0t/S45y5NTMPPCAw2jZOVwEgfvKzrFPMJjzIPz1YXsH2k7nofOxZ7EifH5eWRJ8Kd06E7qz/0GOT4KQ6wwyv9s7ljgP+ytA+0C/9EQTbzYhIHNWXTD23jayH1TY92JP/RlxdSLwELou3ATn1/mHZ0O+jd3UB+6/Kr875dbdM5uGY/7oHDfRc4keaubcfzvpSblU7pOQtnuIiwXYuMmgEAREcJGiWC1OLmEdfKYNXMOA0SytAeTkZkH9khdZTkh5/cHycpuwKoPGxnjQO+mQPe6gAJ7zLYTAUPbVDwGPAEAbbNCEEPtjxdu/OFJcbzQgfj35A0OmmDxkP1nScfpMtLtfTW1RHTOU1HHjFk6NwI+th6CZvGMggpWHa8CTMtZCmyHwNNQZeW9pxKMhSjSB1jTmI9pcI/FWCiwIjJ8kOHZOvoSrYEgOroul+lGb8wMxfwoegPVUXR6RUcxC1MEL94ydJJf1mVe22/l7i/CbQqHgLFJzx4C+Z/RylBUh4LQSjfAr+KwruH1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: github-oauth
    type: Opaque

