apiVersion: apps/v1
kind: Deployment
metadata:
  name: miha
spec:
  template:
    spec:
      containers:
      - name: miha
        image: ghcr.io/catboy-den/miha:edge-main-88cba28-1701814016 # {"$imagepolicy": "flux-system:miha-edge"}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DOTNET_DISCORD__TOKEN
          valueFrom:
            secretKeyRef:
              name: miha-discord-dev
              key: token
        - name: DOTNET_DISCORD__GUILD
          valueFrom:
            secretKeyRef:
              name: miha-discord-dev
              key: guild-id
