apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: miha-dev

namespace: miha
nameSuffix: -dev

resources:
- ../base
- secret-discord.yaml

labels:
- includeSelectors: true
  pairs:
    app: miha
    detail: bot
    stack: dev

patches:
- path: deployment.yaml
- path: metrics.yaml
