apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      version: "6.x"
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo-repo
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - host: podinfo.catboy.rest
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - podinfo.catboy.rest
        secretName: podinfo-gitops-cert
