apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    detail: bot
spec:
  template:
    spec:
      containers:
      - name: miha
        image: ghcr.io/catboy-den/miha:cutting-edge-reduce-logging-dac8b60-1689448023 # {"$imagepolicy": "flux-system:miha-edge"}
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DOTNET_REDIS__HOST
          value: "miha-cutting-edge-redis-service"
        - name: DOTNET_REDIS__PORT
          value: "6379"
        - name: DOTNET_DISCORD__TOKEN
          valueFrom:
            secretKeyRef:
              name: miha-cutting-edge-discord
              key: token
        - name: DOTNET_DISCORD__GUILD
          valueFrom:
            secretKeyRef:
              name: miha-cutting-edge-discord
              key: guild-id
