apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      volumes:
      - name: miha-redis-data
        persistentVolumeClaim:
          claimName: miha-redis-cutting-edge-pvc
