apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: discord
spec:
  encryptedData:
    guild-id: AgBhp5d5pvAHzwCPzpIfVt86KKeBUBqtNNi/uwLvqFZlsWJ5v/PdiaMB3JpAqvo01o7Nbj+a9dWOPgsBbn8BfqLazGfT+OMnYas4MzzKaLqN/3AE5vtEImGEumpN9UTTxjLOuoMjOWZWTeIVQwbwzMR1BR7oE4yvB338rxuYYV6IKb22j8SC9hAJlomOlQQrtg3pGALQy3uJA1K2Q9v9wGKaFRg2aDOpEWmEaSXV/vSQ8B7Jvvfl0/uTWoh5loJM5mwnOiqAsoKAKUOWOiR0MbxlScFHf5fJirrvnsmK5N1wvpq5j1LLkp5gWfzPYAQC5VNZpmH0B/n06UC6YEg0yDX9/6DbcQPh8QmVdh4z5/2LHo1PZW3bcQf6rHnUEJmrt97ghdEDRX//vpr7wRSsgrLULX6GcW4WIlR1FNaQI0Fkg/++ywAmT2WoHXWf1wtV7tK+r3cfKC3rK1BV0AGgMRPLj68E3OO5Srp70PDnnjZrcwkMaLcj4FEZXTQSj5Jiyov+zmOPWKXRDauTYQsnWiP3mAl+e4k/XyYZAbaL7UlgIaH1V5HwYsJJFfO84FNJHeQyJcqcQXDAke5Ws/YbWCmhd9HV1+qSkMDJeddGHQVWTwv+thb/B+WDYffWC8D++G5fqL8SikEUxQM6+up63Lf7CGhhzb2WhUi++QdpeZURiYIaRF7dd61ishvr+gLP0vjDBdSrDd9AvLpKbN2EiwFceJnW
    token: AgAMKakEE/QxYOHlQJFS+qZE1PiF5cK7IeubFu3pXH3OrlHL3Iu3eBXtjRsItOnvGk3FUObj045+85j9mcwmHxjFbWiydNVJo5KRSSTQNZyjcwmC9ES++Ez8+TifgB3hOmDaHkZhqaoH71QHjCuJRIDXNqtC7/29cdXyB2YBs/Z3lYTvreegczip+ZusvNeAYPPiBGr0fjMHGGjy3n/DQnqoes+XMK9G4FiSaYio/IXSoQyUlFsQoP2Otg7ftahpyFpJ0CtuM8/8YZ00RZF4VP6zbCM8fRBjg5VdbBjngVRLyjk15McN1aZspsPwCgIcEggGKrQHgOhAsgv07G4H/z+S1vwebG3TdXmTIydZX04CnZg+hNyBHiM9ujm6LWN2syKhE6SZ+6AoRkOZxHeWQscjdvf2LAX/NuZyuv62jaDVm1aKIEVOjjcjmn2KYAdag5k4qDv/V3GAR8ktRihqWGIR0tdEX5pL9iHBJoSUBQ3+CbkVsscIHwprERRjgn+HrFciQ4kSefYPnXzHIAd0CP+0RIbvO4tjOA5B3a8HF6Sd+IvbkLz9sl0bEhxnq41uc+x2sBnTFSwmPRjgb1pCI1BVXLeCLigKjCdSEJuVdeqWj7A7QAifTVuqMO5RRFRswmtfBlot5GVP8yLwedMUIXfE5h3mDkRZnoo8XZOCp8sptEX/LJgzYNPMdTsq8I9nkvVWmRzqwr6jEAt8V3hlVloQ8GyMgaOQXgEkQdBkkK3ytGzwZkxe+NlNxPpQX0fqNy/j5U48Wr8Vr4vs+i1X3DXdlpEQzdU5PxU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: discord
    type: Opaque
