apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord
  namespace: miha
spec:
  encryptedData:
    guild-id: AgB5vsc75SVQ2I8GWeqFD4WsgIE8hG12Vk+PeEOox4wgTR6qX4S/+RCSCmDzsWD2xRSe04PmuQNgtjfrwyPfJGzuERYO93Qx88Ga8qSyWBvdSjP9gxdPH5EjsFC2fdFK4Tk6H4uwJIJ5pdq+QOvodMw50R5rqn8VO5Y8hbB+TQD4ebPVjccSbLxC/u0XA9UjZy13JnRmNmcLEjh2TP2tKMT68h6R9HvbXBgglgwFT43MRRY645eUQu6F9mjtNhDIR6Cnanl2sQUGDLG2vDk/GkwNmR78l3Z8oEyoFekk/be6YFqt+qg/BJ3JfD+4W2f9CYiGLLvoEzHiQqXUBUuVHuwjhTDzTvnso8vzhWlN2+Cwxl5DNxRwpUt5mm88RdxwBVOyk3xH8EUC22nHUM4kZa9AHuKxPbjjhG9R5dcDyGBiBENae7Y9cTz9hPWWMmKfo1eVHpTxWZtaSlcbLxEEACM+ksa4LTj6hp12RPU/hImPH7qgbrekEM2kiwT3QG1fWtibNB88PJXjJQjbje6jztMXClr31dBT2vhuEYGOQ3SPruMSr19jJrfWua0kIe2VYt1RDHquxNZuUWBYKq+KonPSnNFC1XRf6pYbWeSJ1yH5/s0qDcLSQv6DnEKJ0U3io6TtIxVWzSufwCVvoEPETzm92ZlALmToorkJ7wnFOGnACox0MhrOeDtkrY1ALp22HC9HWPMc5tDkmHl9e601J3RMvThH
    token: AgA321aFAZmKdBE90ctyQA+duBjETrlMIn+A7mv+E4obeDFkZnWeM6b+12iad7Lw7+Ls9Iu7O0HDolHmvueNs49MjNdZvQEK2+ZlD9ew5UkIgMkVIw3pChTUyxk4BIEU5R3uoidKTqD0wfiXwOMydNba7pb5YS9lfKky8iYrwX3eKJNHFr4BYpOh1Po/I9q9saBX4URoYUM6nQOq5DGeGAjDBn9lCQhHGvTnkamxHgH3/Tmiw90GD3LkW1Vxtg401hk4bUTefnXm/ptJpC7mM/EjMKlfR7cr6tfup6EecMNpLo01wBsN1OGgH/FYSJDle2CPY/j6Tau8OkM2kF8DH51Nhf72lD1oyCj/D3Ey4muZS9P8osxOfIJyIEsA+IRODmAsK/EvN9/GcrE4Sn1jz2sh0EXhbBfFHOFxXrH65+RBngFVWYfIrqo0azb8nnRnT9GStOU4j2Xr4UDBncZF0/62U8xc0yt8x7/pRiRDtXhg7FK1mh/kZgPtt2DqtxzIO+cKjAHO85Ep9Z+GCiAsrSoFATU1lDW5k5IrcEYsdPs4qVDgNUht7ThW36SfZnJekCBimQCGYBjAhm6wfpA+BhjJCSSpTUkbZdKAmNAKQDFuumRaGXTfKi7LtVYBMOo8W9A5O1IS7YavTT3v0BtEGjD7q+UW0cPIWTznZ2RyRptrBJmaKR2ETq+7QN2Yxm1o6uFfCwcWE0TTX/nDbajNXVbRMsjuM2XQGvYW18bTofYRZR//oY1npNE4X5R8OZdqSOtFZXSl9AHHgx9RQIcQ0rIJ45wm4F328TY=
  template:
    metadata:
      creationTimestamp: null
      name: discord
      namespace: miha
    type: Opaque
