apiVersion: v1
kind: Secret
metadata:
  name: minio-oidc-auth
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
type: Opaque
stringData:
  clientSecret: ${vault:secret/data/dex-staticClient-secret#secret}
