apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 1h
  chart:
    spec:
      version: "5.x"
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio-repo
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
