apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 1h
  chart:
    spec:
      version: "12.x"
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
      interval: 60m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
