apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 1h
  chart:
    spec:
      version: "5.x"
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio-repo
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # https://github.com/minio/minio/blob/master/helm/minio/values.yaml
  values:
    replicas: 1
    mode: standalone
    persistence:
      enabled: false
      metrics:
        serviceMonitor:
          enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      path: /
      hosts:
      - minio.catboy.rest
      tls:
      - secretName: minio-cert
        hosts:
        - minio.catboy.rest
