apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 1h
  chart:
    spec:
      version: "5.x"
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio-repo
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # https://github.com/minio/minio/blob/master/helm/minio/values.yaml
  values:
    replicas: 1
    resources:
      requests:
        memory: 4Gi
    mode: standalone
    persistence:
      enabled: false
      metrics:
        serviceMonitor:
          enabled: true
    environment:
      MINIO_IDENTITY_OPENID_DISPLAY_NAME: Login with GitHub
      MINIO_BROWSER_REDIRECT_URL: "https://minio.catboy.rest"
    oidc:
      enabled: true
      configUrl: "https://dex.catboy.rest/.well-known/openid-configuration"
      clientId: "minio"
      # Provide existing client secret from the Kubernetes Secret resource, existing secret will have priority over `clientSecret`
      existingClientSecretName: "minio-oidc-auth"
      existingClientSecretKey: "clientSecret"
      claimName: "groups"
      scopes: "openid,profile,email,groups"
      redirectUri: "https://minio.catboy.rest/oauth_callback"
    consoleIngress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      path: /
      hosts:
      - minio.catboy.rest
      tls:
      - secretName: minio-cert
        hosts:
        - minio.catboy.rest
