apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
spec:
  interval: 30m
  chart:
    spec:
      chart: kubed
      version: "0.12.x"
      sourceRef:
        kind: HelmRepository
        name: kubed-repo
      interval: 12h
  # https://github.com/kubeops/config-syncer/blob/v0.13.2/charts/kubed/values.yaml
  values:
    enableAnalytics: false
